In [1]:
import pandas as pd

In [2]:
news = pd.read_csv('news.csv')
news.head()

,source,title,text,publication_date,rubric,subrubric,tags
0,lenta.ru,Синий богатырь,В 1930-е годы Советский Союз охватила лихорадк...,2020-08-30T00:01:00+03:00,Экономика,Госэкономика,NaN
1,lenta.ru,Загитова согласилась вести «Ледниковый период»,Олимпийская чемпионка по фигурному катанию Ал...,2020-08-31T20:04:00+03:00,Спорт,Зимние виды,NaN
2,lenta.ru,Объяснена опасность однообразного питания,Российский врач-диетолог Римма Мойсенко объясн...,2020-08-31T20:07:00+03:00,Из жизни,Еда,NaN
3,lenta.ru,«Предохраняться? А зачем?»,В 2019 году телеканал «Ю» запустил адаптацию з...,2020-08-30T00:04:00+03:00,Интернет и СМИ,ТВ и радио,NaN
4,lenta.ru,Ефремов систематически употреблял наркотики,Актер Михаил Ефремов систематически употребл...,2020-08-31T18:27:00+03:00,Культура,Кино,NaN

In [4]:
# Удаляем столбец tags и добавляем is_fake
news = news.drop('tags', axis=1)
news['is_fake'] = 0
# df = df.drop('tags', axis=1).assign(is_fake=0)

In [5]:
news.head()

,source,title,text,publication_date,rubric,subrubric,is_fake
0,lenta.ru,Синий богатырь,В 1930-е годы Советский Союз охватила лихорадк...,2020-08-30T00:01:00+03:00,Экономика,Госэкономика,0
1,lenta.ru,Загитова согласилась вести «Ледниковый период»,Олимпийская чемпионка по фигурному катанию Ал...,2020-08-31T20:04:00+03:00,Спорт,Зимние виды,0
2,lenta.ru,Объяснена опасность однообразного питания,Российский врач-диетолог Римма Мойсенко объясн...,2020-08-31T20:07:00+03:00,Из жизни,Еда,0
3,lenta.ru,«Предохраняться? А зачем?»,В 2019 году телеканал «Ю» запустил адаптацию з...,2020-08-30T00:04:00+03:00,Интернет и СМИ,ТВ и радио,0
4,lenta.ru,Ефремов систематически употреблял наркотики,Актер Михаил Ефремов систематически употребл...,2020-08-31T18:27:00+03:00,Культура,Кино,0

In [6]:
unique_sorce = news['source'].unique()
print(unique_sorce)

['lenta.ru' 'ria.ru' 'tjournal.ru']

In [7]:
unique_values = news['rubric'].unique()
print(unique_values)

['Экономика' 'Спорт' 'Из жизни' 'Интернет и СМИ' 'Культура' 'Дом'
 'Бывший СССР' '69-я параллель' 'Мир' 'Наука и техника' 'Путешествия'
 'Россия' 'Нацпроекты' 'Силовые структуры' 'Ценности' nan]

In [8]:
count_0 = (news['is_fake'] == 0).sum()
count_1 = (news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 20135
Количество строк с меткой 1: 0

In [9]:
# news = news.dropna(subset=['rubric'])

In [10]:
news.head()

,source,title,text,publication_date,rubric,subrubric,is_fake
0,lenta.ru,Синий богатырь,В 1930-е годы Советский Союз охватила лихорадк...,2020-08-30T00:01:00+03:00,Экономика,Госэкономика,0
1,lenta.ru,Загитова согласилась вести «Ледниковый период»,Олимпийская чемпионка по фигурному катанию Ал...,2020-08-31T20:04:00+03:00,Спорт,Зимние виды,0
2,lenta.ru,Объяснена опасность однообразного питания,Российский врач-диетолог Римма Мойсенко объясн...,2020-08-31T20:07:00+03:00,Из жизни,Еда,0
3,lenta.ru,«Предохраняться? А зачем?»,В 2019 году телеканал «Ю» запустил адаптацию з...,2020-08-30T00:04:00+03:00,Интернет и СМИ,ТВ и радио,0
4,lenta.ru,Ефремов систематически употреблял наркотики,Актер Михаил Ефремов систематически употребл...,2020-08-31T18:27:00+03:00,Культура,Кино,0

In [11]:
lenta_real_news = pd.read_csv('lenta_real_news.csv')
lenta_real_news.head()

,title,link,text,is_fake
0,В российском городе перевернулась машина скоро...,https://lenta.ru/news/2025/09/14/v-rossiyskom-...,В столице произошло серьезное ДТП с участием а...,0
1,Президент Польши согласился на ввод в страну в...,https://lenta.ru/news/2025/09/14/prezident-pol...,ПрезидентПольшиподписал резолюцию о согласии н...,0
2,Президент Польши согласился на ввод в страну в...,https://lenta.ru/news/2025/09/14/prezident-pol...,ПрезидентПольшиподписал резолюцию о согласии н...,0
3,Студент РУДН получил срок за финансирование ИГ,https://lenta.ru/news/2025/09/14/student-rudn-...,2-й Западный окружной военный суд признал студ...,0
4,Россияне открыли на Мальдивах дайвинг-отель дл...,https://lenta.ru/news/2025/09/14/rossiyane-otk...,"Московская пара Ирина и ее муж, более 15 лет ж...",0

In [12]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (lenta_real_news['is_fake'] == 0).sum()
count_1 = (lenta_real_news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 200
Количество строк с меткой 1: 0

In [13]:
panorama_news = pd.read_csv('panorama_news_1.csv')
panorama_news['rubric'] = "Из жизни"
panorama_news.head()

,title,link,text,is_fake,rubric
0,"«Меня можно признать иноагентом, посадить, уби...",https://panorama.pub/news/mena-mozno-priznat-i...,За всю историю «Панорамы» мы не раз приглашали...,1,Из жизни
1,«Выиграл несколько раз в Спортлото»: главный с...,https://panorama.pub/news/vyigral-neskolko-raz...,Глава Совета судей России Виктор Момотов в инт...,1,Из жизни
2,"Ирландский дипломат впал в кому, пытаясь переп...",https://panorama.pub/news/irlandskij-diplomat-...,На дипломатическом приёме в Минске госпитализи...,1,Из жизни
3,Губернатор Вологодской области лично уничтожил...,https://panorama.pub/news/gubernator-vologodsk...,Губернатор Вологодской области Георгий Филимон...,1,Из жизни
4,Суд запретил песню Михаила Шуфутинского «Треть...,https://panorama.pub/news/sud-zapretil-pesnu-m...,Басманный суд столицы полностью удовлетворил и...,1,Из жизни

In [14]:
panorama_economics_news = pd.read_csv('panorama_economics_news.csv')
panorama_economics_news['rubric'] = "Экономика"
panorama_economics_news.head()

,title,link,text,is_fake,rubric
0,Кончилась американская лицензия: c 1 января 20...,https://panorama.pub/news/koncilas-amerikanska...,Американский миллиардер Пол Рокфеллер отказалс...,1,Экономика
1,Сроки добровольной сдачи криптовалюты государс...,https://panorama.pub/news/sroki-dobrovolnoj-sd...,Государство пошло навстречу гражданам и разреш...,1,Экономика
2,ЦРУ: Китай построил 40-миллионный город из пен...,https://panorama.pub/news/cru-kitaj-postroil-4...,Американская разведка сообщила о плачевном сос...,1,Экономика
3,Директор Guinness признался в многолетнем плев...,https://panorama.pub/news/direktor-guinness-pr...,Директор пивоваренной компании Guinness Патрик...,1,Экономика
4,За тёплую погоду в сентябре придётся заплатить...,https://panorama.pub/news/za-tepluu-pogodu-v-s...,"За аномально тёплую погоду в сентябре, наблюда...",1,Экономика

In [15]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (panorama_economics_news['is_fake'] == 0).sum()
count_1 = (panorama_economics_news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 0
Количество строк с меткой 1: 779

In [16]:
panorama_science_news = pd.read_csv('panorama_science_news.csv')
panorama_science_news['rubric'] = "Наука и техника"
panorama_science_news.head()

,title,link,text,is_fake,rubric
0,"Археологи нашли в Помпеях тела двух мужчин, вр...",https://panorama.pub/news/pogibli-vrezavsis-v,"Археологи сообщили, что при исследовании тел д...",1,Наука и техника
1,"В Краснодарском крае тестируют корову, дающую ...",https://panorama.pub/news/v-krasnodarskom-krae...,В ходе реализации всероссийской программы импо...,1,Наука и техника
2,"Сечень, травень, липень: лингвисты предложили ...",https://panorama.pub/news/secen-traven-lipen-l...,Коллектив Института русского языка имени Викто...,1,Наука и техника
3,Бояре поспорили о необходимости поднимать Фёдо...,https://panorama.pub/news/boare-sporat-o-neobh...,В царских палатах Кремля в присутствии Государ...,1,Наука и техника
4,В Великом Новгороде археологи обнаружили второ...,https://panorama.pub/news/v-velikom-novgorode-...,Коллектив археологов из Новгородского государс...,1,Наука и техника

In [17]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (panorama_science_news['is_fake'] == 0).sum()
count_1 = (panorama_science_news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 0
Количество строк с меткой 1: 394

In [18]:
lapsha_feiky_news = pd.read_csv('lapsha_feiky_news.csv')
lapsha_feiky_news['rubric'] = "Интернет и СМИ"
lapsha_feiky_news.head()

,title,link,text,is_fake,rubric
0,Жителей ДНР призывают оставить квартиры военны...,https://lapsha.media/feiky/zhitelej-dnr-prizyv...,В соцсетях и мессенджерах распространяется дип...,1,Интернет и СМИ
1,Жителей ДНР приглашают переехать в Красноярски...,https://lapsha.media/feiky/dnr-pereezd-krasnoj...,В Сети появились обращения глав Красноярского ...,1,Интернет и СМИ
2,От московских диагностических работ школьники ...,https://lapsha.media/feiky/ot-moskovskih-diagn...,"Отпроведения диагностической работы, которая п...",1,Интернет и СМИ
3,Фейки,https://lapsha.media/feiky/page/593/,NaN,1,Интернет и СМИ
4,В России хотят запретить песни Михаила Круга,https://lapsha.media/feiky/v-rossii-hotjat-zap...,В России по предложению Госдумы якобы собирают...,1,Интернет и СМИ

In [19]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (lapsha_feiky_news['is_fake'] == 0).sum()
count_1 = (lapsha_feiky_news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 0
Количество строк с меткой 1: 851

In [20]:
lapsha_feiky_news.isna().sum()

title        2
link         0
text       110
is_fake      0
rubric       0
dtype: int64

In [21]:
# Объединяем датасеты в один
combined_dataset = pd.concat([lapsha_feiky_news, panorama_science_news, panorama_economics_news, panorama_news], ignore_index=True)

# Проверяем результат
combined_dataset.head(100)

,title,link,text,is_fake,rubric
0,Жителей ДНР призывают оставить квартиры военны...,https://lapsha.media/feiky/zhitelej-dnr-prizyv...,В соцсетях и мессенджерах распространяется дип...,1,Интернет и СМИ
1,Жителей ДНР приглашают переехать в Красноярски...,https://lapsha.media/feiky/dnr-pereezd-krasnoj...,В Сети появились обращения глав Красноярского ...,1,Интернет и СМИ
2,От московских диагностических работ школьники ...,https://lapsha.media/feiky/ot-moskovskih-diagn...,"Отпроведения диагностической работы, которая п...",1,Интернет и СМИ
3,Фейки,https://lapsha.media/feiky/page/593/,NaN,1,Интернет и СМИ
4,В России хотят запретить песни Михаила Круга,https://lapsha.media/feiky/v-rossii-hotjat-zap...,В России по предложению Госдумы якобы собирают...,1,Интернет и СМИ
...,...,...,...,...,...
95,Фейки,https://lapsha.media/feiky/page/13/,NaN,1,Интернет и СМИ
96,Финансирование школ ряда регионов пойдет на пр...,https://lapsha.media/feiky/zamorozka-finansiro...,В Сети расходятся постановления о «заморозке» ...,1,Интернет и СМИ
97,В Нижнем Новгороде орудует маньяк,https://lapsha.media/feiky/nizhnij-novgood-man...,"В чатах Нижнего Новгорода пишут, якобы в Сормо...",1,Интернет и СМИ
98,В Запорожской области родителям школьников вып...,https://lapsha.media/feiky/v-zaporozhskoj-obla...,"В Сети распространяется ролик, в котором губер...",1,Интернет и СМИ
99,В России постепенно уничтожают кладбища героев...,https://lapsha.media/feiky/unichtozhenie-kladb...,"В Сети расходится видео, в котором говорится, ...",1,Интернет и СМИ

In [22]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (combined_dataset['is_fake'] == 0).sum()
count_1 = (combined_dataset['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 0
Количество строк с меткой 1: 2062

In [23]:
# Загрузим все три DataFrame (если ещё не загружены)
# news = pd.read_csv('news.csv')  # если ещё не загружен
# lenta_real_news = pd.read_csv('lenta_real_news.csv')  # если ещё не загружен
# combined_dataset = pd.read_csv('combined_dataset.csv')  # если ещё не загружен


# Объединяем все три DataFrame
combined_data = pd.concat([news, lenta_real_news, combined_dataset], ignore_index=True)


# Выбираем только нужные столбцы
selected_columns = combined_data[['title', 'text', 'is_fake']]


# Сохраняем результат в новый CSV файл
selected_columns.to_csv('data_t20000_f2000.csv', index=False)

In [24]:
selected_columns

,title,text,is_fake
0,Синий богатырь,В 1930-е годы Советский Союз охватила лихорадк...,0
1,Загитова согласилась вести «Ледниковый период»,Олимпийская чемпионка по фигурному катанию Ал...,0
2,Объяснена опасность однообразного питания,Российский врач-диетолог Римма Мойсенко объясн...,0
3,«Предохраняться? А зачем?»,В 2019 году телеканал «Ю» запустил адаптацию з...,0
4,Ефремов систематически употреблял наркотики,Актер Михаил Ефремов систематически употребл...,0
...,...,...,...
22392,В России запатентовали не имеющий аналогов спр...,"Иркутская компания «СайберПромТех», специализи...",1
22393,В Госдуме запретили СМИ и блогерам использоват...,Государственная дума единогласно приняла попра...,1
22394,Для безопасности россиян им запретят пересылат...,В России с октября усилят цифровую безопасност...,1
22395,Из Ставропольской краевой думы изгнали депутат...,Ставропольская краевая дума единогласно поддер...,1
22396,"Россияне, работающие в стратегических отраслях...","Россияне, задействованные в стратегических отр...",1

In [25]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (selected_columns['is_fake'] == 0).sum()
count_1 = (selected_columns['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 20335
Количество строк с меткой 1: 2062